### ISSUE TITLE
Is this different from geojson's built in conversion support?

### ISSUE THREAD

**Issue by michaelkirk** [lelongg/geo-geojson#1]
Howdy! 

Just came across this repository and was curious, does this behave differently from the built in support for converting geojson to geo objects?

https://docs.rs/geojson/0.18.0/geojson/#conversion-to-geo-objects

**Comment by lelongg** [comment]
Late answer: geojson's code come from this repository (https://github.com/georust/geojson/pull/122), you should use geojson directly
